export default [
  {
    id: 1,
    desc: "Goggles for Ladies | Blue shades | Sydney Brand | New",
    img: "goggles1.jpg",
    current_price: 315,
    original_price: 399,
    rating: 4.5,
  },
  {
    id: 2,
    desc: "Peach color Leather Bag | Both for casual walks and parties",
    img: "handbag1.jpg",
    current_price: 599,
    original_price: 935,
    rating: 5,
  },
  {
    id: 3,
    desc: "Branded watch | Newly released in last month | First Copy",
    img: "watch1.jpg",
    current_price: 150,
    original_price: 210,
    rating: 4,
  },
  {
    id: 4,
    desc: "Jewellery set for Black dresses | Necklace | Ring | Watch | Earings",
    img: "jewellery.jpg",
    current_price: 855,
    original_price: 1100,
    rating: 3.5,
  },
  {
    id: 5,
    desc: "Fragrance for all types of Folks | Toxin free | Cruely free",
    img: "perfume1.jpg",
    current_price: 305,
    original_price: 500,
    rating: 2,
  },
  {
    id: 6,
    desc: "Men's t-shirt | New Stock | Black in color",
    img: "t-shirt1.jpg",
    current_price: 57,
    original_price: 90,
    rating: 4.5,
  },
  {
    id: 7,
    desc: "Sunglasses to protect undereyes and eyelids | Korean Brand",
    img: "sunglasses.jpg",
    current_price: 78,
    original_price: 120,
    rating: 3.5,
  },
  {
    id: 8,
    desc: "Creme color handbag | Leather | with chain",
    img: "handbag2.jpg",
    current_price: 200,
    original_price: 250,
    rating: 4,
  },
  {
    id: 9,
    desc: "Cherry colored high heels | 4 inch | Limited stock",
    img: "heels2.jpg",
    current_price: 910,
    original_price: 999,
    rating: 1.5,
  },
];
